### ISSUE TITLE
Wrong type argument

### ISSUE THREAD

**Issue by gregnewman** [jrblevin/deft#15]
I have deft installed with no customizations other than file types and directory.  When the buffer opens and I start typing (no matter what the search string is) I constantly get `deft-filter-match-file: Wrong type argument: stringp, nil`.  This is emacs 24.5.1 on Mac.

**Comment by jrblevin** [comment]
Sorry for the delay in replying, but I'm at a loss for what the issue might be. I recall a similar report some time ago, but that one was related to empty files and I've since fixed that. It occurred to me that we could probably narrow it down if you run `M-x toggle-debug-on-error` and send the backtrace.

**Comment by gregnewman** [comment]
It seemed to be an issue with the number of docs I had in nValt.  After cleaning/pruning everything started working properly.  I never did bother to chase down why.

**Comment by jrblevin** [comment]
Glad it is working for you now and thanks for letting me know. I'll close this, but feel free to re-open it if the issue arises again.

**Comment by benmezger** [comment]
I've experienced the same issue on Doom Emacs. Running `doom purge && doom clean` solved this issue.
