### ISSUE TITLE
I write two small functions which could be useful journaling

### ISSUE THREAD

**Issue by chxiaoxn** [jrblevin/deft#28]
I add two small functions for journaling. This is quite useful for myself. I think it could be considered merged into `deft'.

See [https://github.com/chxiaoxn/deft](https://github.com/chxiaoxn/deft).

**Comment by jrblevin** [comment]
Thanks for this. I have a similar feature that I have been working on: naming files with a custom format string (a timestamp) rather than `deft-1`, `deft-2`, and so on. I hope to finish it soon.

The journal file idea is nice, but I don't think it belongs in Deft itself. As you have shown, it can be easily added as an additional function. I have several such functions defined locally myself, tailored to suit my own workflows.

**Comment by chxiaoxn** [comment]
I have some idea of what `Deft` is about, that is why I open a issue first. I hope to see the features you mentioned soon.
