### ISSUE TITLE
deft-text-mode had uses that deft-extensions doesn't serve...

### ISSUE THREAD

**Issue by pobocks** [jrblevin/deft#4]
So, my deft config was as follows: I used deft-file-extension to set the extention to .org, and then used deft-text-mode to trigger a custom minor mode that marked org buffers launched via deft as special. 

I used this to do two things: it let me set up a toggle that would kill or bury all deft buffers at once, and second, so that I could inhibit the hook that cleans trailing whitespace.

Without a non-file-extension way to mark deft buffers, I can't think of an easy way to replicate this functionality.  Would there be general interest in a PR restoring deft-text-mode for explicit use of attaching a minor mode to deft buffers?  Or, alternately, a new variable for same?

**Comment by jrblevin** [comment]
I used to do something similar: My Deft files were all .txt files and so I had `deft-text-mode` set to `markdown-mode`. Otherwise, .txt files aren't special and just open in `text-mode`. With the new `deft-extensions` approach, I now accomplish this using an `auto-mode-alist` entry specifically for .txt files in my `deft-directory` (e.g., `~/deft/`):

    (add-to-list 'auto-mode-alist '("/deft/.*\\.txt\\'" . markdown-mode))

It seems like you could you do something similar with your special minor mode?

**Comment by pobocks** [comment]
That worked! Don't know why I didn't think of that ;-)

Thanks!

**Comment by jrblevin** [comment]
Yes, well, I didn't think of it at first either, which is how `deft-text-mode` came to exist in the first place. I'm happy to retire it now after realizing that it was duplicating functionality. Happy to hear that worked.

**Comment by gnowoel** [comment]
Brilliant. Adding an `auto-mode-alist` entry is even better than the original `deft-text-mode` option, because the major mode for a note would always be consistent, no matter `deft-mode` is enabled or not.
