### ISSUE TITLE
Multiple directory

### ISSUE THREAD

**Issue by gongzhitaao** [jrblevin/deft#6]
Dr. Blevins, thanks for this awesome work!

I have been using Deft for quite a while, it is really fantastic for keeping notes.  However I find it more convenient if I could keep my notes in separate places.  I'm aware of the updated feature `deft-recursive`, but still I may find supporting separate folders a good feature.

*Proposed modification*
Change `deft-directory`.  Instead of satisfying `stringp`, we can make it a list, satisfying `listp`.

Is this a reasonable feature?  May I submit a PR on it or maybe you are already working on it?

Thanks

**Comment by jrblevin** [comment]
Since the main idea behind Deft is that it should be simple and mostly stay out of the way, I tend to be conservative about adding new complexity. Supporting multiple directories raises other questions. For example, if we allow multiple directories where are new files created? Probably in the first directory of the list, but then how do we specify that we want to create a file in a second, or third directory? Where do we archive files? It would be best to think through these design questions before coding anything up.

Just thinking through the alternatives of multiple directories in a single Deft instance, I thought of two:

1. I saw this Gist some time ago and thought it seemed promising: [deft-in-dir.el](https://gist.github.com/doitian/4291851). It allows one to create multiple Deft instances for browsing different directories. I actually started working on implementing this officially but didn't finish. I'd be happy to share that code if you wanted to take over.

2. For files in dir1 and dir2, you could use symbolic links in a couple of ways: an overall notes directory with symbolic links to dir1 and dir2 (notes/dir1 -> dir1, notes/dir2 -> dir2, point Deft at notes) or simply a link to dir2 as a subdirectory of dir1 (dir1/dir2 -> dir2, point Deft at dir1). Depending on how the notes are related, one of these approaches might make sense.

**Comment by vyp** [comment]
symbolic links is what I do. It's the best and simplest way to solve this without actually changing deft. I think there's a case where if the symlinked files is under vcs, emacs will prompt if you want to follow it or not, but that can be bypassed be setting something in .emacs. Also, it will be annoying to change the symlink if the original file/directory is moved, but I still think symlinks are the way to go.

**Comment by gongzhitaao** [comment]
@jrblevin Yeah, I agree that it is actually more problematic to add this feature.  The `deft-in-dir.el` is really promising.  Looking forward to your next release.
@vyp Cool, never thought of it.  I was using `helm-projectile` to search files.  I would definitely try this symbolic link.
