### ISSUE TITLE
About Performance

### ISSUE THREAD

**Issue by strongwillow** [jrblevin/deft#8]
Hi,

I've been using deft and markdown as my note-taking tool chain for like, half a year now . Now I have 40+ notes now and it works fine.

My concern is, if my notes grow up to 500+, will there be a performance issue? I'm not familiar with Lisp and I didn't see through your code. Hope you can give us  a simple answer on this.

Thanks!

Qing

**Comment by jrblevin** [comment]
At the moment I have 720 files in Deft. Some are small but a good number of them are in the 50K-200K range. Acceptable performance is subjective, but it's certainly good enough for me at this point.

For some insight into the internals: Deft prioritizes performance over memory usage. It reads all files when it is first loaded (or reloaded later) in order to generate the titles, dates, and summaries. It keeps the full contents in memory for filtering later. I'm sure `deft-filter-match-file` could be optimized, but aside from that the fundamental limiting factor is how fast `re-search-forward` can search the in-memory full-content strings.

There are some notes about performance in the documentation. In short, if it becomes a problem you can always fall back to static filtering (one-time search, as opposed to incremental filtering) with `C-c C-l`.

**Comment by strongwillow** [comment]
Thanks for the internals. I think it's better to use multiple deft folders.
